package com.braincamp.salarypusher.domain.model

/**
 * A single coin that reached the front edge of the pusher and was collected.
 *
 * This is a domain event — it records that real salary was earned.
 * Stored in Room via [EarningEventEntity].
 *
 * [id] is auto-generated by Room; defaults to 0 for unsaved instances.
 * [amountCents] is always positive and equals [denomination.valueInCents].
 * [timestamp] is epoch milliseconds (UTC).
 */
data class EarningEvent(
    val id: Long = 0,
    val amountCents: Long,
    val timestamp: Long,
    val denomination: CoinDenomination
)
